apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: sql
  labels:
    app: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 3
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: 467336339185.dkr.ecr.us-east-1.amazonaws.com/mysql:v1.2
        name: sql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: pw
        ports:
        - containerPort: 3306