apiVersion: v1
kind: Pod
metadata:
  labels:
    app: employees
  name: pod_webapp
spec:
  containers:
  - image: 467336339185.dkr.ecr.us-east-1.amazonaws.com/webapp:v1.1
    name: con_webapp
    env:
    - name: DBHOST
      value: 10.244.0.5
    - name: DBPORT
      value: "3306"  
    - name: DBUSER
      value: root
    - name: DATABASE
      value: employees
    - name: DBPWD
      value: pw
    - name: APP_COLOR
      value: blue  
    ports:
    - containerPort: 8080
